Features/filter product by price
khang3999/RunTrail pull request #19
Opened 2024-10-12 09:47 UTC by Datto098

2024-10-12 09:48 UTC, Datto098 commented
Update project directory, Update filter product by discount price

2024-10-12 10:30 UTC, 10102004tan commented on backend/src/main/java/runtrail/dev/backend/controller/SpuController.java
cho ví dụ tại sao ở đây giá dùng double

2024-10-12 10:59 UTC, Datto098 commented on backend/src/main/java/runtrail/dev/backend/controller/SpuController.java
Nảy test cái làm tròn giá nên chuyển qua Double thử =)), [Đã sửa lại]

2024-10-12 15:40 UTC, tranhieuphuc12 submitted a review, later dismissed
no issue, be able to merge

2024-10-12 16:35 UTC, Charcasbeos requested changes
When I enter the maximum price with a 20-digit number, the interface overflow

2024-10-13 00:31 UTC, Datto098 commented
> When I enter the maximum price with a 20-digit number, the interface overflow

Updated

2024-10-13 00:44 UTC, chiendevj approved these changes, later dismissed
successfully to do.

2024-10-13 01:34 UTC, DoNgocHieu approved these changes
oke success , done

2024-10-13 01:34 UTC, khang3999 approved these changes
Great

2024-10-13 01:35 UTC, Charcasbeos approved these changes
It's oke

2024-10-13 01:36 UTC, merged